sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker pull openjdk:11-jdk-slim

jobs:
  include:
    - stage: "Build"
      name: "Build the project"
      script: mvn package -DskipTests=true
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: mvn test
    - script: mvn verify -PIntegration
      name: "Integration Tests"     # names the second Tests stage job
