sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker pull openjdk:11-jdk-slim
  - chmod +x mvnw
  - docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

jobs:
  include:
    - stage: "Build"
      name: "Build the project"
      script: ./mvnw package -DskipTests=true
    - stage: "Tests"
      name: "Unit Tests"
      script: ./mvnw test
    - script: ./mvnw verify -PIntegration
      name: "Integration Tests"
